apiVersion: apps/v1
kind: Deployment
metadata:
  name: gm-tools-api
spec:
  selector:
    matchLabels:
      app: gm-tools-api
  template:
    metadata:
      labels:
        app: gm-tools-api
    spec:
      containers:
      - name: gm-tools-api
        image: ghcr.io/rkochenderfer/gm-tools-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      
---

apiVersion: v1
kind: Service
metadata:
  name: gm-tools-api
spec:
  selector:
    app: gm-tools-api
  ports:
  - port: 3030
    targetPort: 3000
